### PR TITLE
Add Timezone for conversational action

### PR DESCRIPTION
**Pull request by freiSMS**
Conversational actions are sending timezone information in each request.
This information is added to the timezone plugin.

### CODE REVIEW

**Comment by freiSMS** [comment]
@rmtuckerphx I tested this version with a local npm install.

**Comment by dominik-meissner** [comment]
Hey @rmtuckerphx it would be great if you would merge and release this! We have a project waiting to take this change live.

**Comment by freiSMS** [comment]
Hi @rmtuckerphx , did you have the time to take a look at this? Thanks!

**Review by rmtuckerphx — APPROVED** [review]

**Comment by rmtuckerphx** [comment]
@freiSMS Published to npm as v1.2.0

**Comment by freiSMS** [comment]
Great @rmtuckerphx . Thanks!

**Pull request merged**
